"""first migration

Revision ID: 6c2478c4c606
Revises: 902b9b371685
Create Date: 2024-04-13 18:42:41.935239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c2478c4c606'
down_revision: Union[str, None] = '902b9b371685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('scrape1')
    op.drop_constraint('scrape_user_id_fkey', 'scrape', type_='foreignkey')
    op.drop_column('scrape', 'user_id')
    op.drop_column('scrape', 'owner_id')
    op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.add_column('scrape', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('scrape', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('scrape_user_id_fkey', 'scrape', 'user', ['user_id'], ['id'])
    op.create_table('scrape1',
    sa.Column('job_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_Names', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_titles', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posted_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('job_id', name='scrape1_pkey')
    )
    # ### end Alembic commands ###
