"""auto

Revision ID: 85bd4f27bb27
Revises: c69033f4a3ae
Create Date: 2024-03-11 13:37:37.787250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '85bd4f27bb27'
down_revision: Union[str, None] = 'c69033f4a3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('users')
    #op.drop_table('scrape1')
    op.add_column('scrape', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('scrape_user_fk', 'scrape', type_='foreignkey')
    op.create_foreign_key(None, 'scrape', 'user', ['user_id'], ['id'])
    #op.drop_column('scrape', 'owner_id')
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    #op.drop_constraint('user_email_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.drop_column('user', 'phone_number')
    op.add_column('scrape', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scrape', type_='foreignkey')
    op.create_foreign_key('scrape_user_fk', 'scrape', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('scrape', 'user_id')
    op.create_table('scrape1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('companyNames', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_titles', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='scrape1_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
