"""auto

Revision ID: ecf7dfbc1e37
Revises: 6c2478c4c606
Create Date: 2024-04-14 13:03:50.567839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf7dfbc1e37'
down_revision: Union[str, None] = '6c2478c4c606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape1')
    op.drop_table('scrape_table')
    op.add_column('scrape', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scrape', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scrape', type_='foreignkey')
    op.drop_column('scrape', 'user_id')
    op.create_table('scrape_table',
    sa.Column('companyNames', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_titles', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('scrape1',
    sa.Column('job_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_Names', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_titles', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('posted_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('Location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('job_id', name='scrape1_pkey')
    )
    # ### end Alembic commands ###
